from level_class import *

levels = []

levels.append(Level('Impossible?',
                    ["How hard can it be?",
                     "There are fake exit blocks!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                         P",
                        "P                                         P",
                        "P                                         P",
                        "P         P   P         P      P     F    P",
                        "PP  P             P                       P",
                        "P                 PPP                     P",
                        "P  DDDDDDDDDDDDDDDDDDPPHHHHHDDPPHH  HDDDDDP",
                        "P                                H  H     P",
                        "P                                H  H     P",
                        "P                                H  H     P",
                        "PD                               H  H     P",
                        "P                                H  H     P",
                        "P   D                            H  H     P",
                        "P                                         P",
                        "P                                         P",
                        "PD                                        P",
                        "PD  D                             HH  L   P",
                        "PE  D                                    EP",
                        "PPDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=0.1))

levels.append(Level('Impossible? Part II',
                    ["Is it truly harder?",
                     "Which one is the real exit block?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                   H     P",
                        "P                                    H    P",
                        "P                                P    H   P",
                        "P                                 P    H  P",
                        "P  PPPPPPPDDDDPPDDDDDDDPDDDDDDPIIPPP      P",
                        "P                                 P H     P",
                        "P                                P   H    P",
                        "PII                                       P",
                        "P                                       PPP",
                        "P         P   P                           P",
                        "PP  P             P            LL     P   P",
                        "P                 PPP                     P",
                        "P  DDDDDDDDDDDDDDDDDDPHHHHHHHHHHHH  HHHHHHP",
                        "P                                P  H     P",
                        "P                          P     P  H     P",
                        "PMMMMMMM                   P     P  H     P",
                        "P      H                   P     H  P     P",
                        "P      HHHMMMMMMMMMMM      P     H  P     P",
                        "P                          P     H  P     P",
                        "P                          P              P",
                        "PH                                        D",
                        "P                                         D",
                        "PL  H                             HH      D",
                        "PE  H                             LLD    FP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=14.4))

levels.append(Level('Triple the fun',
                    ["Combining some blocks in three layers"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P                                    B      B",
                        "PP H                                 B      B",
                        "P   H                                B     BB",
                        "P   H   HhPHhPHH                    BB H  BBP",
                        "P   H                               B  B    P",
                        "P    HHH           H      H     L   B  B    P",
                        "P               PPDDDPP          BB   B  L  P",
                        "P                                  BBB DDDD P",
                        "PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH       P",
                        "P                                     PPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P   WWWWWWWW      WWWWWW  I  I LWWWWHHL     P",
                        "P   HHHHHHHHHHHHSSHHHHHHHHIHHIHHHHHHHHHHHHHHP",
                        "PL     S   S              D  D    D   D     P",
                        "P      S   S    S HHH        D              P",
                        "P    S   S      S       L                   P",
                        "P    S   SH     SSSSS           H     D    EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=60.0))

levels.append(Level('Triple the fun Hard',
                    ["Combining dangerous blocks in three layers"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P                                    B      B",
                        "PM H                      D          BH     B",
                        "P   H                                B     BB",
                        "P   H   HhPHhPHH                    BB H  BBP",
                        "P   H                               B  B    P",
                        "P    HHH           H      H     L   B  B    P",
                        "P               PPDDDPP          BB   B  P  P",
                        "P                                  BBB DDDD P",
                        "PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH       P",
                        "PL                                    PPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P   WWWWWWWW      WWWWWW  I  I  WWWWHHL     P",
                        "P   HHHHHHHHHHHHSSHHHHHHHPIIIIIHHHHHHHHHHHHHP",
                        "P      SH LS          H   DDDD    D   D     P",
                        "P      S   S    S HHH        D              P",
                        "P    S   S      S      HL                   P",
                        "P    S   SH     SSSSS           H     D    EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDPPPP",
                    ],
                    fast_time=40.0))
