from level_class import *

levels = []

# P = platform, M = Right carpet, W = left carpet, e = exit, s = sticky, b = bouncy, l = life, D = pit, h = hurt.


levels.append(Level("Rainbow block!!!",
                    ["Rainbow block!!!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=2.0))
levels.append(Level("Hurty,Hurty and Hurt",
                    ["Hurty,Hurty and Hurt"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "PHHHH  HHHHHHHHHHHHHHHHHP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=5.0))

levels.append(Level("Heal, heal, heal",
                    ["Heal, heal, heal"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                   LL  P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPLPPP",
                    ],
                     fast_time=3.5))



levels.append(Level("Bouncy",
                    ["Bouncy"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PBBBBBBBBBBPPPPPPPPPPPPPP",
                    ],
                     fast_time=3.0))




levels.append(Level("All",
                    ["Bouncy"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "PPPPP          PPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                  H    P",
                        "P                  H    P",
                        "P                  H    P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                  H    P",
                        "P                  H    P",
                        "P                  H    P",
                        "P                  H   EP",
                        "PDDDDDBBBBBBBBBBDDDPPLLPP",
                   ],
                     fast_time=5.0))



levels.append(Level("Rainbow block!!!",
                    ["Rainbow block!!!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                EP",
                        "P                                PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                               P",
                        "P                               P",
                        "P          BBBBBBBBBBBBBBB      P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "PH          HHH HH  HHH   HH    P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P LP",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                               P",
                        "P                            UUUP",
                        "P               HHHHHHHHHHH  IIEP",
                        "PPPPPUUUUUUUUUPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=13.0))
