from level_class import *

levels = []

levels.append(Level('Impossible?',
                    ["How hard can it be?",
                     "There are fake exit blocks!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                         P",
                        "P                                         P",
                        "P                                         P",
                        "P         P   P         P      P     F    P",
                        "PP  P             P                       P",
                        "P                 PPP                     P",
                        "P  DDDDDDDDDDDDDDDDDDPPHHHHHDDPPHH  HDDDDDP",
                        "P                                H  H     P",
                        "P                                H  H     P",
                        "P                                H  H     P",
                        "PD                               H  H     P",
                        "P                                H  H     P",
                        "P   D                            H  H     P",
                        "P                                         P",
                        "P                                         P",
                        "PD                                        P",
                        "PD  D                             HH  L   P",
                        "PE  D                                    EP",
                        "PPDPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=0.1))

levels.append(Level('Impossible? Part II',
                    ["Is it truly harder?",
                     "Which one is the real exit block?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                   H     P",
                        "P                                    H    P",
                        "P                                P    H   P",
                        "P                                 P    H  P",
                        "P  PPPPPPPDDDDPPDDDDDDDPDDDDDDPIIPPP      P",
                        "P                              DD P H     P",
                        "P                                P   H    P",
                        "PII         U                          H  P",
                        "P                                       PPP",
                        "P         P   P                           P",
                        "PP  P             P            LL     P   P",
                        "P                 PPP                     P",
                        "P  DDDDDDDDDDDDDDDDDDPHHHHHHHHHHHH  HHHHHHP",
                        "P                               EP  H     P",
                        "P      D                   P     P  H     P",
                        "PMMMMMMM                   P     P  H     P",
                        "P      H                   P     H  P     P",
                        "P      HHHMMMMMMMMMMM      P     H  P     P",
                        "P                          P     H  P     P",
                        "P                          P              P",
                        "PH                                        D",
                        "P                                         D",
                        "PL  H                             HH      D",
                        "PE  H                             LLD    FP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPUPPPPPPPPPPPP",
                    ],
                    fast_time=14.4))

levels.append(Level("Flying course",
                    ["Up, still more up, and lots of up."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P    P      E      PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P     HDH     PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P  HD     DH  PPPPPPP",
                        "P    P      U      PPPPPPP",
                        "P    P  L       L  PPPPPPP",
                        "P    P L         L PPPPPPP",
                        "P    PBB    BB   BBPPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P    P    P   PPPPPPP",
                        "P  S PH         P  PPPPPPP",
                        "PS  SP H           PPPPPPP",
                        "P S  P  H   HH     PPPPPPP",
                        "P   SP   H         PPPPPPP",
                        "P  S P    H        PPPPPPP",
                        "P S  P         H   PPPPPPP",
                        "P    P          H  PPPPPPP",
                        "P    P       U     PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P             PPPPPPP",
                        "P    P   P         PPPPPPP",
                        "P    P   PP         PPPPPP",
                        "P    P   PP          PPPPP",
                        "P    P   PP        P PPPPP",
                        "P    P   PP        P LPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        PPPPPPP",
                        "P    P   PP        IIPPPPP",
                        "P    P   PP        PIPPPPP",
                        "P        PP       PIIPPPPP",
                        "P        PP   PPPPPIIIPPPP",
                        "P        PP        PPIIPPP",
                        "P        II        PPPIIPP",
                        "PPPPPPUUPPPPPDDDDDDPPPPPPP",
                    ],
                    fast_time=18.0))

levels.append(Level('Triple the fun',
                    ["Combining some blocks in three layers"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P                                    B      B",
                        "PP H                                 B      B",
                        "P   H                                B     BB",
                        "P   H   HhPHhPHH                    BB H  BBP",
                        "P   H                               B  B    P",
                        "P    HHH           H      H     L   B  B    P",
                        "P               PPDDDPP          BB   B  L  P",
                        "P                                  BBB DDDD P",
                        "PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH       P",
                        "P                                     PPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P   WWWWWWWW      WWWWWW  I  I LWWWWHHL     P",
                        "P   HHHHHHHHHHHHSSHHHHHHHHIHHIHHHHHHHHHHHHHHP",
                        "PL     S   S              D  D    D   D     P",
                        "P      S   S    S HHH        D              P",
                        "P    S   S      S       L                   P",
                        "P    S   SH     SSSSS           H     D    EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=60.0))

levels.append(Level('Triple the fun Hard',
                    ["Combining dangerous blocks in three layers"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P                                    B      B",
                        "PM H                      D          BH     B",
                        "P   H                                B     BB",
                        "P   H   HhPHhPHH                    BB H  BBP",
                        "P   H                               B  B    P",
                        "P    HHH           H      H     L   B  B    P",
                        "P               PPDDDPP          BB   B  P  P",
                        "P                                  BBB DDDD P",
                        "PHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH       P",
                        "PL                                    PPPPPPP",
                        "P                                           P",
                        "P                                           P",
                        "P   WWWWWWWW      WWWWWW  I  I  WWWWHHL     P",
                        "P   HHHHHHHHHHHHSSHHHHHHHPIIIIIHHHHHHHHHHHHHP",
                        "P      SH LS          H   DDDD    D   D     P",
                        "P      S   S    S HHH        D              P",
                        "P    S   S      S      HL                   P",
                        "P    S   SH     SSSSS           H     D    EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPDDPPPP",
                    ],
                    fast_time=40.0))

levels.append(Level('Crazy 2.0',
                    ["How crazee can it be?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P     P                                  LP",
                        "P     P                                  LP",
                        "P    PE        D        DPP         SS  DHP",
                        "P   PPPPPPPPLPPPPPPPPPPPPP PPPSDS     S   P",
                        "P                               S      SS P",
                        "P                               S       S P",
                        "PPHUHHHHHHHD  DHHHHHHHHHHH  L   S       S S",
                        "P                            L          P S",
                        "P                                       P S",
                        "P                       P               P S",
                        "P                      HEDH    PPPPPPPPPP S",
                        "P   PP                   PH    P    HHHHH S",
                        "I HH   PPPPPPPPPPPPPPPPD PPPPPPP    HHHHH P",
                        "IP    P   P   PPPPPP   P PP   PP P        P",
                        "I PP    P   P   P    P  P   P    PPPPPPPPPP",
                        "P PP    P   P   P    P      P    PPPPPPPPPP",
                        "P   PPPPPPPPPP  PPP PPPPPPPPPPPPPPPPPPPPPPP",
                        "P        P                                P",
                        "PIP      PMM  WWPPPP     DDD  EEEEEEEEEEEEP",
                        "PEP      P      P                         P",
                        "P P      P  WW  P    P                    P",
                        "P        P P  P P                         P",
                        "P        P      P        P          P     P",
                        "PP       PMM  MMP   P                     P",
                        "PP       P      P           P             P",
                        "P   PP      PP  PPDDDDDDD       DDDDDDDDDPP",
                        "P               PE       DDDEDDD         EP",
                        "P        P WWMM PL                       LP",
                        "PPPPPPPPPPPPPPPPPGGGGGGGGGGGGGGGGGGGGGGGGGP",
                    ],
                    fast_time=4.0))

