
level_messages = []
levels = []


level_messages.append(["Go for the pink portal block!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                      EP",
    "PPPPDDDPPDDDDPPPPPPPPPPPP", ])
level_messages.append(["The act of jumping",
                       "Here's a test."])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                          PP          P",
    "P                      P               P",
    "P                                     EP",
    "P                    P            PPPPPP",
    "P                PP                    P",
    "P              P                       P",
    "P            P P                       P",
    "P        PP    P          PP    PP     P",
    "P      P              PP               P",
    "P     P                  PP            P",
    "P                      P   PP          P",
    "P PP                           PP      P",
    "P              P             PP        P",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", ])
level_messages.append(["Don't get hurt with the red lava blocks,",
                       "But if you do, heal with the teal water blocks."])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                PLP    P",
    "P                 P     P",
    "P                      EP",
    "PPPPHHHPPHHHHPPHHHHHHHHPP", ])
level_messages.append(["More practice avoiding lava"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                                      P",
    "P                                      P",
    "P                   P   P              P",
    "P                       P      P       P",
    "P              P        P      P       P",
    "P                       P      P       P",
    "P          P            P      P       P",
    "P          PP           P      P       P",
    "P                       P      P       P",
    "P              PPPPP    P      P       P",
    "P                   P   P              P",
    "P                       P              P",
    "P                    PLLP              E",
    "PPPHHHPPPHHHPPPPPHHHPPPPPPPPPHHHPPPHHPPP", ])
level_messages.append(["You can stick to all sides of sticky blocks",
                       "Try it by jumping onto them."])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "S                S      P",
    "S               S      EP",
    "S                 SSSSSSP",
    "S  PHHHHHHPS           SP",
    "S  SSSSSSSSS  PS       SP",
    "S                      SP",
    "PPPPHHHHHHHHSSSSSSSSSSSSP", ])
level_messages.append(["Here is a fun loop-de-loop!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       P              P",
    "P                       PSSSSSSSSSSSSSSS",
    "P                       P              S",
    "P                       P PPPPPPPHPPPP S",
    "P                       P  P     P     S",
    "P                       P  P           S",
    "P                       P  P           S",
    "P        SSSSSSSSSSSSSSSPE P           S",
    "P                       SSSSSSS        S",
    "P                    PP                S",
    "P                      PP      SSSSSSSSS",
    "P  P              P     P               L",
    "P                       P              P",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", ])
level_messages.append(["You can bounce on the bouncy blocks for a while,",
                       "But don't fall into the pit!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P           PPPP        P",
    "P      SP P        B    P",
    "PSS B                   P",
    "P                      EP",
    "PPPPDDDDDDDDDDDDDDDDPPPPP", ])
level_messages.append(["STAY AWAY FROM THAT PIT!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P           SSSSSSSSS   P",
    "P          P            P",
    "P         B             P",
    "P    B P                P",
    "P                      EP",
    "PPPPDDDDDDDDDDDDDDDDDPPPP", ])
level_messages.append(["Can you go the wrong way on a moving carpet?"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                      EP",
    "PPPWWWWWWWWWMMMMMMMMPPPP", ])
level_messages.append(["Up the staircase!"])
levels.append([
    "PPPPPPPPPPPPPPPPSSLPPPPPP",
    "P               S       P",
    "P               S      EP",
    "P               S    PPPP",
    "P                 P     P",
    "P                       P",
    "P               PPPPP   P",
    "P               P      PP",
    "P               P     P P",
    "PP                   P  P",
    "P                   P   P",
    "P                 P     P",
    "P                P     PP",
    "P          PPPP         P",
    "P              P        P",
    "P               P       P",
    "P                PPP    P",
    "P                  P    P",
    "P                    P  P",
    "PPPPPPPPPPDDDPPPPPPPPPPPP", ])
level_messages.append(["Putting the blocks together."])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P            SSSS    PPPP",
    "P                   P   P",
    "P                 PP    P",
    "P           PP     PP   P",
    "P     PB   PBP          P",
    "P   SB     S PB         P",
    "PP         S   P        P",
    "P         B             P",
    "P                       P",
    "P                  P    P",
    "P        P     P        P",
    "P                       P",
    "P           P           P",
    "P               P       P",
    "P                       P",
    "P                   P   P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ])
level_messages.append(["Sometimes, falling is inevitable"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P               S    SPPP",
    "P                S   S  P",
    "P                  SSS  P",
    "P                S S    P",
    "P                       P",
    "P                       P",
    "PP             P        P",
    "P                       P",
    "P                       P",
    "P                  P    P",
    "P        P     P        P",
    "P                       P",
    "P           P           P",
    "P               P       P",
    "P                       P",
    "P                   P   P",
    "PPDDDPPDDDDDDDPPDPPPPPPPP", ])
level_messages.append(["Now would be a bad time to fall :("])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P            SSSS SSSPPPP",
    "P                 S     P",
    "P                       P",
    "P        P  PP          P",
    "P      B                P",
    "P  PP     L             P",
    "PP                      P",
    "P  P   SPPB             P",
    "P  PPHHP                P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PDDDDDDDDDDDDDDDDDDDDDDDP", ])
level_messages.append(["Practice with stickies!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PPPPS                   P",
    "P    S                  P",
    "P      S                P",
    "P    S                  P",
    "P      S                P",
    "PS  S  HHHHHHHHHHHHHHHHHP",
    "PS  H  H                P",
    "PS   HH                 P",
    "PS                      P",
    "PH                      P",
    "PH SSP        SSS       P",
    "PH                   L  P",
    "PHHHHH                 EP",
    "PPPPPPDDDDDDDDPPPPPPPPPPP", ])
level_messages.append(["That's a LOT of LAVA!!!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                      EP",
    "P                    PPPP",
    "P                   P   P",
    "P                P P    P",
    "P      SB    SP         P",
    "P                       P",
    "P   PHHHHHHHHHHHHPL     P",
    "PPP  HHHHHHHHHHHHP      P",
    "P  PHHHPPPPPPPPPPP      P",
    "P  PPPPP                P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PDDDDDDDDDDDDDDDDDDDDDDDP", ])
level_messages.append(["Oh, No! The lava spilled!",
                       "It is possible to take no damage. Try it!",
                       "It's a REAL challenge!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               S      EP",
    "P            SSSS SPPPHPP",
    "P         P     S     HHP",
    "P         P     S     HHP",
    "P  PHHPP  P PSSSS SSS HHP",
    "P  PPHH   B B   S     HPP",
    "P     H P B B   P       S",
    "PP    HH  B B       PS  S",
    "PH PHHHHHPB B           S",
    "PH PHHHPH B B     S     S",
    "P  HHPPBH B B    S  SSSPP",
    "P HHHHHBH B   P         P",
    "P  HHHHBH B             P",
    "PH HHHHHH BBB   P       P",
    "P  HSSSPHP   B          P",
    "P PPPPPPPP      P  P    P",
    "P                    P  P",
    "PPPPPPPPPPPPPPPPPPPPPPPLP", ])