from level_class import *

levels = []

levels.append(Level('The beginning',
                    ["Go for the rainbow portal block!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                P      P",
                        "P                 P     P",
                        "P   PPPPPPPPPPPPPPPP    P",
                        "P                 P     P",
                        "P                P      P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level('Jumping',
                    ["The act of jumping.",
                     "Hold up to jump bigger.",
                     "Up is hard, down is easy."],
                    [
                        "PPPPPPPIIIIPPPPPPPPPPPPPPPPPPPPPPIIIIIPP",
                        "P                                      P",
                        "P       P                              P",
                        "P      PLP                             P",
                        "P     P P P                            P",
                        "P       P    P                         P",
                        "P       P        P         PP          P",
                        "P       P              P               P",
                        "P                                     EP",
                        "P                    P            P  PPP",
                        "P                PP              P     P",
                        "P              P               PPP     P",
                        "P            P P             P         P",
                        "P        PP    P           P           P",
                        "P      P                PP             P",
                        "P     P              PP     PP         P",
                        "P                   P                  P",
                        "P PP              PP                   P",
                        "P              P                       P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level('Hurt blocks',
                    ["Don't get hurt with the red lava blocks,",
                     "But if you do, heal with the GOLDEN life blocks."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P         PP            P",
                        "P        PPPP           P",
                        "P       PPPPPP          P",
                        "P       PPPPPP          P",
                        "P        PPPP           P",
                        "P        PPPP           P",
                        "P         PP            P",
                        "P                       P",
                        "P         PP            P",
                        "P         PP            P",
                        "P                       P",
                        "P                       P",
                        "P                 LP    P",
                        "P                PP     P",
                        "P                      EP",
                        "PPPPhhhPPhPhhPPhhhhhhhhPP",
                    ]))

levels.append(Level('OOF!',
                    ["More hurt blocks, YAY!",
                     "Through the wall?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                             P              P",
                        "P                             P              P",
                        "P                             P              P",
                        "P     PP       PP     PPPP    P              P",
                        "P    P  P     P  P    P       P              P",
                        "P   P    P   P    P   PPPP    P              P",
                        "P   P    P   P    P   P       P   H          P",
                        "P    P  P     P  P    P                      P",
                        "P     PP       PP     P                      P",
                        "P                                            P",
                        "P                             P      P       P",
                        "P                             P      P       P",
                        "P                         PP  P      P       P",
                        "P                             P      P       P",
                        "P                     PPP     P      P       P",
                        "P                             P      P       P",
                        "P              PPPPP          P      P       P",
                        "P                   P         P              P",
                        "P                             P              P",
                        "P                    PPPPhhLhhP              E",
                        "PPPhhhPPPhhhPPPPPhhhPPPPPPPPPPPPPPPhhhPPPhhPPP",
                    ],
                    fast_time=8.4))

levels.append(Level('First Sticky',
                    ["You can stick to all sides of sticky blocks",
                     "Try it by jumping onto them."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "S                S      P",
                        "S               S      EP",
                        "S                 SSSSSSP",
                        "S  SSSSSSSSS           SP",
                        "S  SSSSSSSSS  PS       SP",
                        "S                      SP",
                        "PPPPhhhhhhhhSSSSSSSSSSSSP",
                    ]))

levels.append(Level('Loop-de-loops',
                    ["Here are some fun loop-de-loops with stickies!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPSSSSSSSSSSSSSSSSSSS",
                        "P   S              S       S   S   S S",
                        "P   S              S         S   S   S",
                        "P   S              S SSSSSSSSSSSSSS SS",
                        "P   S              S             LS  S",
                        "P   S              S              SS S",
                        "S   P              SSSSSSSSSSSSSSSS  S",
                        "S   P                         SSSSS SS",
                        "S   P                          SSSS  S",
                        "S   P               SSSSSSSSS  S   S S",
                        "S   P               SSSSSSSSSS   S   S",
                        "P   S              SSSSSSSSSSSSSSSSSSS",
                        "P   S              S                 S",
                        "P   S              S                 S",
                        "P   S              S  SSSSSSSSSSSSS  S",
                        "P   S              S  S           S  S",
                        "P   S              S  S           S  S",
                        "S   P              S  S  SSSSSSS  S  S",
                        "S   P              S  S       ES  S  S",
                        "S   P              S  S        S  S  S",
                        "S   P              S  SSSSSSSSSS  S  S",
                        "S   P    SSSSSSSSSSS              S  S",
                        "S        SSSSSSSSSSS              S  S",
                        "S       S          SSSSSSSSSSSSSSSS  S",
                        "P                P                   S",
                        "P                S                   S",
                        "P                PSSSSSSSSSSSSSSSSSSSS",
                        "P  P         P   PSSSSSSSSSSSSSSSSSSSS",
                        "P                PSSSSSSSSSSSSSSSSSSSS",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ],
                    fast_time=18.3))

levels.append(Level("Let's FLY!",
                    ["Once you land on the green block, tap jump multiple times to fly!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPUUDDHHDDHHHDDHHPPPPPPP",
                    ]))

levels.append(Level("Up we go",
                    ["Set your eyes to the sky!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P   P          E         P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P         H          P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   PH                   P",
                        "P   P         U          P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P H             H    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P                    P",
                        "P   P       H            P",
                        "P                        P",
                        "P                        P",
                        "PPPPPPUUPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level('Wheee!!!!',
                    ["There must be a way over those walls."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  P                               P",
                        "P  P                               P",
                        "P  P      PPPPPPP       PPPPPP     P",
                        "P  P                               P",
                        "P  P                               P",
                        "P  P                               P",
                        "P                                  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P  P",
                        "P     P            P            P EP",
                        "PPPPUUPPPPPPPPPUUUPPPPPPPPPPUUUPPPPP",
                    ],
                    fast_time=6.7))

levels.append(Level("Up, up, and away!",
                    ["Can you make it to the top?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  P        H         P  P",
                        "P  P       H          P  P",
                        "P  P      H              P",
                        "P  P     H           P   P",
                        "P  P    H            P   P",
                        "P  P   H        U    P   P",
                        "P  P  H              P   P",
                        "P  P H               P   P",
                        "P  PH                P   P",
                        "P  P                 P   P",
                        "P  P                 P   P",
                        "P  P                 P   P",
                        "P  P        P        P   P",
                        "P  P  U      P       P   P",
                        "P  P          P      P   P",
                        "P  P           P     P   P",
                        "P  PP           P    P   P",
                        "P  P P           P   P   P",
                        "P  P  P           P  P   P",
                        "P  P   P           P P   P",
                        "P  P    P           PP   P",
                        "P  P        U        P   P",
                        "P  P  P              P   P",
                        "P  P   P             P   P",
                        "P  P    P       P    P   P",
                        "P  P     P       P   P   P",
                        "P  P      P       P  PP PP",
                        "P  P       P       P P   P",
                        "P  P        P       PP   P",
                        "P            P       P   P",
                        "P                    P   P",
                        "PPPPPPPPPPPPPPPPUUPPPPFDEP",
                    ]))

levels.append(Level('First bouncy',
                    ["You can bounce on the bouncy blocks for a while,",
                     "But don't fall into the pit!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P           PPPP        P",
                        "P      SP P        B    P",
                        "PSS B                   P",
                        "P                      EP",
                        "PPPPDDDDDDDDDDDDDDDDPPPPP",
                    ],
                    fast_time=3.2))

levels.append(Level('Boing!',
                    ["STAY AWAY FROM THAT PIT!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P           BBB         P",
                        "P                       P",
                        "P         B             P",
                        "P    B P                P",
                        "P                      EP",
                        "PPPPDDDDDDDDDDDDDDDDDPPPP",
                    ],
                    fast_time=3.2))

levels.append(Level('Stairs',
                    ["Up the staircase!"],
                    [
                        "PPPPPPPPPPPPPPPPSSPPPPPPP",
                        "P               S       P",
                        "P               S      EP",
                        "P               S    PPPP",
                        "P                 P     P",
                        "P                       P",
                        "P               PPPPP   P",
                        "P               P      PP",
                        "P               P     P P",
                        "PP                   P  I  P",
                        "P                   P   I  P",
                        "P                 P     P",
                        "P                P      P                      L",
                        "P          PPPP        PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P              P        P",
                        "P               P       P",
                        "P                PPP    P",
                        "P                  P    P",
                        "P                    P  P",
                        "PPPPPPPPPPDDDPPPPPPPPPPPP",
                    ],
                    fast_time=5.6))

levels.append(Level('First moving carpet',
                    ["Ride the moving carpets!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "PPPMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP    P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P            P     P     P            P",
                        "P  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWP",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P      P        h         H           P",
                        "PMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP   LP",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P      h                   P          P",
                        "P      P       P           P          P",
                        "P  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWP",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "PMMMMMM   MMMMMMMMM     MMMMMMMMMM    P",
                        "PPPPPPP   PPPPPPPPP     PPPPPPPPPP    P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                                     P",
                        "P                        P            P",
                        "P                  P                  P",
                        "P                                     P",
                        "P             PP                      P",
                        "P      h    P            P            P",
                        "P  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWP",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P             H                       P",
                        "P                                     P",
                        "P                  HHHH               P",
                        "P                                     P",
                        "P                                    EP",
                        "PMMMMMDDDDMMMMMMMMMMMMMMMMMMMMDDDDPLPPP",
                    ],
                    fast_time=24.0))

levels.append(Level('Wrong way?',
                    ["Can you go the wrong way on a moving carpet?"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "PPPMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMM  P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP  P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P  WWWWWWWWWWWWWWWMMMMMWWWWWWWWWWWWWP",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P          P        P               P",
                        "PMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMM   P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P  WWMMMMMWWW    WWWMMMMMWWWWWWWWWWWP",
                        "P  PPPPPPPPPP    PPPPPPPPPPPPPPPPPPPP",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                                   P",
                        "P                          P        P",
                        "P        P                 P       EP",
                        "PMMMMMMMMMWWWWWMMMMMMMMMMMMMWWWMMMPPP",
                    ],
                    fast_time=15.4))

levels.append(Level('Ice blocks',
                    ["Slide on the ice!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "PPGGGGGGGGGGGGGGGGGGGG  P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P   GGGGGGGGGGGGGGGGGGGGP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "PGGGGGGGGGGGGGGGGGGGG   P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P    H       H          P",
                        "P   GGGGGGGGGGGGGGGGGGGGP",
                        "P                       P",
                        "P                  L    P",
                        "P                       P",
                        "P   GGGGGGGGGGGGGGGGGGGGP",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPGGGGGGGGGGGGGGGGGGGGPPP",
                    ],
                    fast_time=14.0))

