level_messages = []
levels = []

# P = platform, M = Right carpet, W = left carpet, e = exit, s = sticky, b = bouncy, l = life, D = pit, h = hurt.

level_messages.append(["Pink block!!!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                      EP",
    "PPPPPPPPPPPPPPPPPPPPPPPPP", ])

level_messages.append(["Hurty,Hurty and Hurt"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PHHHH  HHHHHHHHHHHHHHHHHP",
    "P                       P",
    "P       HHHHHHHHHHHHHHHHP",
    "P                       P",
    "P              L        EP",
    "PPPPPPPPPPPPPPPPPPPPPPPPP", ])


level_messages.append(["HONEY!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                      EP",
    "P                     S  P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P              SSSSSS S P",
    "P              S      L P",
    "P              S      S P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S      S P",
    "P              SSSSSS S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "PPPPPPPPPPPPPPPPPPPPPPPPP", ])


level_messages.append(["HONEY!"])
levels.append([
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                      EP",
    "P                     S  P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P              SSSSSS S P",
    "P              S      L P",
    "P              S      S P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S     LS P",
    "P              S     SS P",
    "P              S     SS P",
    "P              S      S P",
    "P              SSSSSS S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S L",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     SLP",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P                     S P",
    "P HHHHHHHHHHHHHHHHHHH S P",
    "PPPPPPPPPPPPPPPPPPPPPPPPP", ])
