from level_class import *

levels = []

# P = platform, M = Right carpet, W = left carpet, e = exit, s = sticky, b = bouncy, l = life, D = pit, h = hurt.


levels.append(Level("Rainbow block!!!",
                    ["Rainbow block!!!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level("Hurty,Hurty and Hurt",
                    ["Hurty,Hurty and Hurt"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "PHHHH  HHHHHHHHHHHHHHHHHP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level("Heal, heal, heal",
                    ["Heal, heal, heal"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                   LL  P",
                        "P                      EP",
                        "PPPPPPPPPPPPPPPPPPPPPLPPP",
                    ]))


levels.append(Level("Bouncy",
                    ["Bouncy"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                       P",
                        "P                      EP",
                        "PBBBBBBBBBBPPPPPPPPPPPPPP",
                    ]))
