NUM_LEVELS = 12

levels = [[] for x in range(NUM_LEVELS)]

levels[0] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                                      P",
    "P                           P          P",
    "P                                      P",
    "P                                      P",
    "P                    P            P    P",
    "P                                      P",
    "P                                      P",
    "P            P                         P",
    "P                                      P",
    "P                                      P",
    "P     P                                P",
    "P                                      P",
    "P                                      P",
    "P                                     EP",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP", ]
levels[1] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P          E            P",
    "P                       P",
    "P                       P",
    "P              P   P    P",
    "P                       P",
    "P                     LLP",
    "P                     LEP",
    "PPPHHHPPPHHHPPPPPHHHPPPPP", ]
levels[2] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       L",
    "P                       P",
    "P                       P",
    "P                 P     P",
    "P                      EP",
    "PPPPHHHPPHHHHPPHHHHHHHHPP", ]
levels[3] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                      EP",
    "P                      SP",
    "P  HHHHHHHHH           SP",
    "P  SSSSSSSSS     S     SP",
    "P                      SP",
    "PPPPHHHHHHHHSSSSSSSSSSSSP", ]
levels[4] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P           PPPP        P",
    "P      SP P        B    P",
    "PSS B                   P",
    "P                      EP",
    "PPPPDDDDDDDDDDDDDDDDPPPPP", ]
levels[5] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P           SSSSSSSSS   P",
    "P          P            P",
    "P         B             P",
    "P    B P                P",
    "P                      EP",
    "PPPPDDDDDDDDDDDDDDDDDPPPP", ]
levels[6] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                      EP",
    "PPPWWWWWWWWWMMMMMMMMPPPP", ]
levels[7] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P            SSSS    PPPP",
    "P                   P   P",
    "P                  P    P",
    "P           PP B PPPP   P",
    "P     PBSSPPB           P",
    "P  PP                   P",
    "PPP                     P",
    "P  P   PPPB             P",
    "P  PPHHP                P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ]
levels[8] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P            SSSS S  PPPP",
    "P                 S P   P",
    "P              SSS P    P",
    "P           PP   PPPP   P",
    "P      B  PPB           P",
    "P  PP                   P",
    "PP                      P",
    "P  P   PPPB             P",
    "P  PPHHP                P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ]
levels[9] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               P       P",
    "P               P      EP",
    "P            SSSS    PPPP",
    "P                 P     P",
    "P                       P",
    "P           PPPPPBPPP   P",
    "P               P      PP",
    "P  SSS          P     P P",
    "PP                   P  P",
    "P  P   PPP          P   P",
    "P  PPHHP          P     P",
    "P                P     PP",
    "P          PPPP         P",
    "P              P        P",
    "P               P       P",
    "P                PPP    P",
    "P                  P    P",
    "P                    P  P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ]
levels[10] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P               PL      P",
    "P               P      EP",
    "P            SSSS PPPPPPP",
    "P                     HHP",
    "P         P             P",
    "P         P PSSSSBSSS   P",
    "P  SSS    B B   P      PP",
    "P         B B   P     P P",
    "PP        B B        P  P",
    "P  P   PPPB B       P   P",
    "P  PPSSP  B B     P     P",
    "P      B  B B    P     PP",
    "P      B  B   P         P",
    "P      B  B    P        P",
    "P         BBB   P       P",
    "PH HSSS      B     P    L",
    "P               P  P    P",
    "P                    P  P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ]
levels[11] = [
    "PPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                       P",
    "P                      EP",
    "P                    PPPP",
    "P                   P   P",
    "P                  P    P",
    "P      SB    SB  P      P",
    "P                       P",
    "P   PHHHHHHHHHHHH       P",
    "PPP        L            P",
    "P  P   PPPB             P",
    "P  PPHHP                P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "P                       P",
    "PPWWWWWWPPMMMMMMMPPPPPPPP", ]
