from level_class import *

levels = []

levels.append(Level("Let's do this!",
                    ["Go for the rainbow portal block!",
                     "Press up or space to jump."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P      P     P       P        P      P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP      P",
                        "P                                    P",
                        "P                                    P",
                        "P  P      P      P           PP      P",
                        "P  P      P      P           P       P",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P               PPPPPPPPPPPPPPPPPPPPPP",
                        "P            P         P       P     P",
                        "P    PPP     P                       P",
                        "P    PP      P                       P",
                        "P    PP      P       P       P      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ], fast_time=14.1))

levels.append(Level('Watch Your Step',
                    ["Don't fall in the black pits!",
                     "If you go fast enough you might get a prize..."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                   P",
                        "P                                                   P",
                        "P                                                   P",
                        "P                                                   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  IPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP         IPPPP  PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP          PPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP          P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP  EP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPPDDPPPPPPPDDPPPPPDDPPPPPDDPPPPPDDPPPPPDDPPPPPPPPP",
                    ], fast_time=8.7))


levels.append(Level('Hot Stuff',
                    ["Watch out for red blocks, they burn!",
                     "Look for glowing yellow health blocks to heal!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P      h     h       h        H      P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP      P",
                        "P                                    P",
                        "P                                    P",
                        "P  H      H      h           Ph      P",
                        "P  P      P      P           P       P",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P               PPPPPPPPPPPPPPPPhhh  P",
                        "P            h         P       P     P",
                        "P     PP     PP                      P",
                        "P     P      P                       P",
                        "P     P      P       P       P      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ], fast_time=15.0))


levels.append(Level('Trampoline',
                    ["Bounce on!",
                     "After you jump hold up/space for extra bounce.",
                     "You can also jump just before you hit a bounce for a boost"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  P       PPI                       P",
                        "P  P       PLI                       P",
                        "P  P       PPP                       P",
                        "P  P                                 P",
                        "P  P                                EP",
                        "P          PPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P      PPPPP                         P",
                        "P                                    P",
                        "P             P     P     P     P   EP",
                        "P       PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P      PP  H     H     H      H      P",
                        "P                                    P",
                        "P       P     P     P      P        EP",
                        "P      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P             P         P           EP",
                        "PBBPPPPPhhhhhPPPhhhhhhhPPPhhhhhhhhPPPP",
                    ]))


levels.append(Level('Sticky Climb-n-Drop',
                    ["Climb on the sticky blocks!",
                     "Push away to let go."],
                    [
                        "PPPPPPPPPPPIIIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPIIIIIPPP",
                        "P  P                             B        B    E  SDDDDDDDDDDDDDDDDDDDDD",
                        "P  P        B                   B        B        S",
                        "P  S       B B          B           B   B         S",
                        "P  S      L   B         B          B   B          S",
                        "P  S          B        PB         B               S",
                        "P  S         B        PPB       BBBBBB            P",
                        "P  S        P       PPPPP            BBBBBBBBBBBBBP",
                        "P  S        P                 P                   P",
                        "P  S        B              P     P     P     P    P",
                        "P  S                PPPPPPPPPBBBPPPPPPPPPPPPPPPP  P",
                        "P  S                    B     B     B      B      S",
                        "P  S                                              S",
                        "P  S                       B     B      B         S",
                        "P  S                PPPPPPPPPPPPPPPPPPPPPPPPPPPP  S",
                        "P  S                                              S",
                        "P                                                 S",
                        "P                                                 P",
                        "P                          P         P            P",
                        "PBBPPPPPBBBBBPPPPPPPPhhhhhPPPhhhhhhhPPPhhhhhhhhPPPP",
                    ]))


levels.append(Level('Hanging Tough',
                    ["Check out the sticky blocks!",
                     "Push down to let go."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  PSSSSSSSSSSSSSSSSSSSSSSSS            P",
                        "P  P           HH                       P",
                        "P                                     L P",
                        "P                                       P",
                        "PPPPP                                   P",
                        "P   PhhhhhhhhPPPPPhhhhhhhhhhhSSSSSSSSS  P",
                        "P                                    P  P",
                        "P                                    H  P",
                        "S   PP                               H  S",
                        "S   PP        P     P     P     P    P  S",
                        "S   PP  PPPPPPPPPPPPPPPPPPPPPPPPPPP  P  S",
                        "S   PP  P  H     H     H      H      S  H",
                        "S   SP  P                            S  H",
                        "P   SP  P     P     P      P         S  S",
                        "P   SP  PE    P     P      P         S  S",
                        "P   SP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPH  S",
                        "S   S     SSSPPPSSSSSSSPPPSSSSSSSSSSSH  P",
                        "S                                       P",
                        "P                                       P",
                        "P             P         P               P",
                        "PPPPPPPPhhhhhPPPDDDDDDPPPPPhhhhhhhhPPPPPP",
                    ], fast_time=25.0))


levels.append(Level("Moving Sidewalks!",
                    ["Get your speed up for some LONG jumps!",
                     "Remember to hold up/space for bigger jumps."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                             B   S",
                        "P                                      P                       P                       P      B   S",
                        "S                                      P                       P                       P      B   S",
                        "S MMMMMMMMM          MMMMMMMMMM        P       MMMMMMMMM       P       MMMMMMMMM       P      B   S",
                        "S                                      P                       P                       P P    B   P",
                        "S                                      P                       P                       PEP        P",
                        "S          WWWWWWWWWWWWWWWWWWWWWWWWWWWWW                                               PPP        S",
                        "S                                                                                                 S",
                        "S                                                                                                 S",
                        "S                                                                                                 S",
                        "S          WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW                      P",
                        "S                                                                                                 P",
                        "S                                                                                                 S",
                        "S                                                                           MMMMMMMMMMMMMMMMMMM   S",
                        "S                                                                                                 S",
                        "S                 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW                           S",
                        "P                                                                                                 S",
                        "P                                                                                                 P",
                        "PPPPPBBBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPhhhhhhhP",
                    ],
                    fast_time=7.7))

levels.append(Level('Watch Your Step, Part II',
                    ["Leaps of Faith!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                        P",
                        "P                                                                        P",
                        "P                                                                        P",
                        "P                                                                        P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPPHHPPPPPHHPPPPPHHPPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPL  P       P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPP  S       P",
                        "PPPPP  PPPPPPP  PPPPP                    P   PPPP  PPPPP  PPPPP  S       P",
                        "PPPPP  PPPPPPP  PPPPP                        PPPP  PPPPP  PPPPP  S       P",
                        "PPPPP  PPPPPPP  PPPPP                        PPPP  PPPPP  PPPPP  S       P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPP  S  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPI  PPPPP  S       P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP          PPPP  SPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP                    B  PPPPP  PPPPP         PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPP  H       P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPS  P  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP                      PPPPPP  PPPPP  PPPPS  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP                       PPPPP  PPPPP  PPPPS  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP           BBBB    PPPPPSSSS  PPPPP  PPPPS  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP           BEEB     SSSSSSSS  PPPPP  PPPPS  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP                              PPPPP  PPPPS  P       P",
                        "PPPPP  PPPPPPP  PPPPP                           PPPPPPPP  PPPPS  PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP                              PPPPP  PPPPS          P",
                        "PPPPP  PPPPPPP  PPPPP            PS                PPPPP  PPPPS  PP      P",
                        "PPPPPDDPPPPPPPDDPPPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPPPDDPPPPPDDPPPPPPPPP",
                    ],
                    fast_time=26.0))


levels.append(Level("Tricky Sticky!",
                    ["A sticky situation..."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P          P              P",
                        "P          P              P",
                        "P          P       P      P",
                        "P          P             EP",
                        "PPPPP   PPPPPPPS       PPPP",
                        "P             PS       PPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP P        SPPP",
                        "P          SP          SPPP",
                        "P          PP          PPPP",
                        "P          PP          PPPP",
                        "PPP        PPPP        PPPP",
                        "PPP        PP P        PPPP",
                        "PPP        PP P        PPPP",
                        "PPP        PP P        PPPP",
                        "PPPDDDDDDDDPPPPDDDDDDDDPPPP",
                    ]))


levels.append(Level("Chaos!",
                    ["Mayhem!",
                     "Insanity!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                                                                                                P",
                        "P           L           H             H         P                   P               P                    P           P                    P      P",
                        "P                                               PLLLLLLLLLLLLLLLLLLLP               PLLBBBBBLLBBBBBBLLBBLP           PSSSHHSSSHHSSSHHSSSHHP      P",
                        "P                                                                                                                                                P",
                        "P                      hHh           hHh       hhhhhhhhhhhhhhhhhhhhhhh             hhhhhhhHHhhhhhhHHhhHHhhh         BBBhhBBBhhBBBhhBBBhhBBL      P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP      P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                                P",
                        "P         L                                                                                                                                      P",
                        "P                                     H            h     H                                                                                       P",
                        "P                       H                         H           H       L                                                                          P",
                        "PP                                                                                                                                               P",
                        "P                                    hHh                hHh                                                                                      P",
                        "P                      hHh           PPP          hHh   PPPWWWWWWWWWWWWWWWWWWWWW     MWHHMWMWHHMWMWHHMWMW              MWMWMWMWMWMWMWMWMWMW      P",
                        "P     PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                                                                                                P",
                        "P                                                                                                                                    P     E     P",
                        "P                                                                                                                                   PP           P",
                        "P                                                                                                                                  PPP           P",
                        "P                                                                                                                                 PPMP           P",
                        "P                                                                                                                                PPWWP           P",
                        "P                                                                                                                               PPMMMP           P",
                        "P                                                                                                                              PPWWWWP           P",
                        "P                               L                                   L                    L                      L             PPMMMMMP           P",
                        "P                                                                                                                            PPWWWWWWP           P",
                        "P                                                                                                                           PPMMMMMMMP           P",
                        "PPPPPPPPPPPPPPPPP P P P H P P P   P P M H M P P  M M M H W W W PPPPPPPPPPP P P P H P P P   P P M H M P P  W W W H W W W PPPPPPPPPPPPPP           P",
                        "PPPPPPPPPPPPPPPPPHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHPPPPPPPPPPPDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDPPPPPPPPPPPPPPIPPPPPPPPPPP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPIIIIIIIIIIIP",
                        "P                                                                                                                                    P           P",
                        "P                                                                                                                                    P           P",
                        "P                                                                                                                                    I           P",
                        "P                                                                                                                                    I           P",
                        "P                                                                                                                                   PP           P",
                        "P                                                                                                                                   PP          BP",
                        "P                                                                                                                                   PP B      B  P",
                        "P                                                                                                                                   PPB  B  B  B P",
                        "P                                                                                                                                   PP  B  B     P",
                        "P                                                                                                                                   PPBB B   B  BP",
                        "P                                                                                                                                   PP B  B   B  P",
                        "P                                                                                                                                   PPB  B  HB  BP",
                        "P                                                                                                                                   PP  B  B  B  P",
                        "P                                                                                                                                   PPB  B   B  BP",
                        "P                                                                                                                                   PP B  B   B  P",
                        "P                                                                                                                                   PPB  B  B  B P",
                        "P                                                                                                                                   PP  B  B  B  P",
                        "P                                                                                                                                   PPB  B   B  BP",
                        "P                                                                                                                                   PP B  B   B  P",
                        "P                                                                                                                                   PPB  B  B  B P",
                        "P                                                                                                                                   PP  H  B  B  P",
                        "P                                  P P    P P                                                                                       PPL  B   B  BP",
                        "P                                  PPP    PPP                                                                                       PP     H  H  P",
                        "P                                  PPPPPPPPPP                                                                                       PP          BP",
                        "P                                    PP  PP                                                                                         PPhBh B B BBBP",
                        "P                                    PPPPPP                                                                                                      P",
                        "P                             P P P  PP  PP  P P P                                                                                               P",
                        "P                             PPPPP  PPPPPP  PPPPP                                                                                           B   P",
                        "P                             PP PP  PPPPPP  PP PP                                                                                          BB   P",
                        "P                              PPPPPPPPPPPPPPPPPP                                                                                          BB    P",
                        "P                              PPPPPPPPEEPPPPPPPP                                                                                         BB     P",
                        "P                              PPPPPPPPEEPPPPPPPP          D     I     L     W     M     B     S     H     h     P                       BB      P",
                        "P                              PPPPPPPPEEIIIIIIII                                                                                                P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))