from level_class import *

levels = []

levels.append(Level('Some Name',
                    ["Go for the pink portal block!",
                     "Press up to jump."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P      P     P       P        P      P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP      P",
                        "P                                    P",
                        "P                                    P",
                        "P  P      P      P           PP      P",
                        "P  P      P      P           P       P",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P               PPPPPPPPPPPPPPPPPPPPPP",
                        "P            P         P       P     P",
                        "P    PPP     P                       P",
                        "P    PP      P                       P",
                        "P    PP      P       P       P      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))

levels.append(Level('Some Name',
                    ["Don't fall in the black pits!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                   P",
                        "P                                                   P",
                        "P                                                   P",
                        "P                                                   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  IPPPP  PPPPP  P       P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP         IPPPP  PPPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP          PPPP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP          P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PPPPPP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP  EP",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P  PP   P",
                        "PPPPP  PPPPPPP  PPPPP  PPPPP  PPPPP  PPPPP  P       P",
                        "PPPPPDDPPPPPPPDDPPPPPDDPPPPPDDPPPPPDDPPPPPDDPPPPPPPPP",
                    ]))


levels.append(Level('Some Name',
                    ["Watch out for red blocks!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P      h     h       h        H      P",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP      P",
                        "P                                    P",
                        "P                                    P",
                        "P  H      H      h           Ph      P",
                        "P  P      P      P           P       P",
                        "P  PPPPPPPPPPPPPPPPPPPPPPPPPPPPLLPPPPP",
                        "P                                    P",
                        "P                                    P",
                        "P               PPPPPPPPPPPPPPPPhhh  P",
                        "P            h         P       P     P",
                        "P     PP     PP                      P",
                        "P     P      P                       P",
                        "P     P      P       P       P      EP",
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                    ]))


levels.append(Level('Some Name',
                    ["Bounce on!",
                     "Hold up for extra bounce."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  P                                 P",
                        "P  P                                 P",
                        "P  P                                 P",
                        "P  P                                 P",
                        "P  P                                EP",
                        "P          PPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P      PPPPP                         P",
                        "P                                    P",
                        "P             P     P     P     P   EP",
                        "P       PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P      PP  H     H     H      H      P",
                        "P                                    P",
                        "P       P     P     P      P        EP",
                        "P      PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP P",
                        "P                                    P",
                        "P                                    P",
                        "P                                    P",
                        "P             P         P           EP",
                        "PBBPPPPPhhhhhPPPhhhhhhhPPPhhhhhhhhPPPP",
                    ]))


levels.append(Level('Sticky Climb-n-Drop',
                    ["Climb on the sticky blocks!",
                     "Push away to let go."],
                    [
                        "PPPPPPPPPPPIIIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPIIIIIPPP",
                        "P  P                             B        B    E  SDDDDDDDDDDDDDDDDDDDDD",
                        "P  P        B                   B        B        S",
                        "P  S       B B          B           B   B         S",
                        "P  S      L   B         B          B   B          S",
                        "P  S          B        PB         B               S",
                        "P  S         B        PPB       BBBBBB            P",
                        "P  S        P       PPPPP            BBBBBBBBBBBBBP",
                        "P  S        P                 P                   P",
                        "P  S        B              P     P     P     P    P",
                        "P  S                PPPPPPPPPBBBPPPPPPPPPPPPPPPP  P",
                        "P  S                    B     B     B      B      S",
                        "P  S                                              S",
                        "P  S                       B     B      B         S",
                        "P  S                PPPPPPPPPPPPPPPPPPPPPPPPPPPP  S",
                        "P  S                                              S",
                        "P                                                 S",
                        "P                                                 P",
                        "P                          P         P            P",
                        "PBBPPPPPBBBBBPPPPPPPPhhhhhPPPhhhhhhhPPPhhhhhhhhPPPP",
                    ]))


levels.append(Level('Hanging Tough',
                    ["Check out the sticky blocks!",
                     "Push down to let go."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P  PSSSSSSSSSSSSSSSSSSSSSSSS            P",
                        "P  P           HH                       P",
                        "P                                   L   P",
                        "P                                       P",
                        "PPPPP                                   P",
                        "P   PhhhhhhhhPPPPPhhhhhhhhhhhSSSSSSSSS  P",
                        "P                                    P  P",
                        "P                                    H  P",
                        "S   PP                               H  S",
                        "S   PP        P     P     P     P    P  S",
                        "S   PP  PPPPPPPPPPPPPPPPPPPPPPPPPPP  P  S",
                        "S   PP  P  H     H     H      H      S  H",
                        "S   SP  P                            S  H",
                        "P   SP  P     P     P      P         S  S",
                        "P   SP  PE    P     P      P         S  S",
                        "P   SP  PPPPPPPPPPPPPPPPPPPPPPPPPPPPPH  S",
                        "S   S     SSSPPPSSSSSSSPPPSSSSSSSSSSSH  P",
                        "S                                       P",
                        "P                                       P",
                        "P             P         P               P",
                        "PPPPPPPPhhhhhPPPDDDDDDDPPPhhhhhhhhhPPPPPP",
                    ]))


levels.append(Level("Moving Sidewalks!",
                    ["Get your speed up for some LONG jumps!"],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                                 P",
                        "P                                                                                             B   S",
                        "P                                      P                       P                       P      B   S",
                        "S                                      P                       P                       P      B   S",
                        "S MMMMMMMMM          MMMMMMMMMM        P       MMMMMMMMM       P       MMMMMMMMM       P      B   S",
                        "S                                      P                       P                       P P    B   P",
                        "S                                      P                       P                       PEP        P",
                        "S          WWWWWWWWWWWWWWWWWWWWWWWWWWWWW                                               PPP        S",
                        "S                                                                                                 S",
                        "S                                                                                                 S",
                        "S                                                                                                 S",
                        "S          WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW                      P",
                        "S                                                                                                 P",
                        "S                                                                                                 S",
                        "S                                                                           MMMMMMMMMMMMMMMMMMM   S",
                        "S                                                                                                 S",
                        "S                 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW                           S",
                        "P                                                                                                 S",
                        "P                                                                                                 P",
                        "PPPPPBBBBPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPhhhhhhhP",
                    ],
                    fast_time=7.5))


levels.append(Level("Tricky Sticky!",
                    ["A sticky situation..."],
                    [
                        "PPPPPPPPPPPPPPPPPPPPPPPPPPP",
                        "P          P              P",
                        "P          P              P",
                        "P          P       P      P",
                        "P          P             EP",
                        "PPPPP   PPPPPPPS       PPPP",
                        "P             PS       PPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP PS       SPPP",
                        "P PS       SP P        SPPP",
                        "P          SP          SPPP",
                        "P          PP          PPPP",
                        "P          PP          PPPP",
                        "PPP        PPPP        PPPP",
                        "PPP        PP P        PPPP",
                        "PPP        PP P        PPPP",
                        "PPP        PP P        PPPP",
                        "PPPDDDDDDDDPPPPDDDDDDDDPPPP",
                    ]))